CREATE TABLE `item_despesa_importado` (
	`id` int AUTO_INCREMENT NOT NULL,
	`periodoCustoId` int NOT NULL,
	`lancamentoCustoId` int,
	`equipamentoTag` varchar(100) NOT NULL,
	`equipamentoDescricao` varchar(255),
	`equipamentoSistemaId` int,
	`classificacao` varchar(50) NOT NULL,
	`sequencia` varchar(20),
	`data` varchar(20),
	`produto` varchar(500) NOT NULL,
	`grupoProduto` varchar(255),
	`quantidade` decimal(12,3) DEFAULT '0',
	`custo` decimal(12,2) NOT NULL DEFAULT '0',
	`centroCusto` varchar(20),
	`hodometro` decimal(12,2),
	`intervalo` decimal(12,2),
	`horaPorLitro` varchar(20),
	`litrosPorHora` varchar(20),
	`observacoes` text,
	`userId` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `item_despesa_importado_id` PRIMARY KEY(`id`)
);
